package de.jensklingenberg.ktorfit.internal

import de.jensklingenberg.ktorfit.Ktorfit

/**
 * This will be implemented by classes that
 * are generated by Ktorfit-Ksp.
 */
public interface KtorfitService {
    public var ktorfit: Ktorfit

    public fun setKtor(ktorfitClient: Ktorfit) {
        this.ktorfit = ktorfitClient
    }
}

/**
 * This will be used as default parameter for [Ktorfit.create].
 * When this class is used at runtime, it means that the compiler plugin
 * did not replace the default parameter with the right class
 */
internal class DefaultKtorfitService : KtorfitService {
    override lateinit var ktorfit: Ktorfit
}